import type { Organization, Match, SavedGrant } from "../types";

export const DEMO_ORG_ID = "demo-org-001";

export const demoOrg: Organization = {
  id: DEMO_ORG_ID,
  name: "Horizon Youth Center",
  orgType: "NONPROFIT",
  mission:
    "We empower under-resourced youth through STEM education, mentorship, and after-school programming to build pathways out of poverty.",
  location: "Chicago, IL",
  city: "Chicago",
  state: "IL",
  budgetSize: "FROM_100K_TO_500K",
  focusAreas: ["Youth Development", "STEM", "Education", "Mental Health"],
  staffCapacity: "SIX_TO_TWENTY",
  website: "https://horizonyouthcenter.org",
};

export const demoMatches: Match[] = [
  {
    id: "m1",
    orgId: DEMO_ORG_ID,
    grantId: "g1",
    score: 96,
    effortLevel: "LOW",
    summary:
      "This grant funds STEM-focused after-school programs serving youth in underserved urban communities, with awards ranging from $10,000 to $25,000. Nonprofits with 501(c)(3) status operating in major metropolitan areas are eligible to apply. The application requires a one-page program narrative, a simple budget, and two letters of support.",
    reasoning:
      "Near-perfect alignment — funder explicitly prioritizes urban STEM youth programs matching Horizon's exact mission. Low staff burden fits your capacity.",
    grant: {
      id: "g1",
      externalId: "grants.gov-445821",
      title: "Community Tech Equity Grant",
      funder: "The Lovelace Foundation",
      deadline: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
      amountMin: 10000,
      amountMax: 25000,
      eligibility: ["Nonprofits (501c3)", "City governments"],
      description: "Supports technology access and STEM education in underserved communities.",
      category: ["STEM Education", "Technology Access"],
      sourceUrl: "https://www.grants.gov/search-results-detail/445821",
      source: "grants.gov",
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "m2",
    orgId: DEMO_ORG_ID,
    grantId: "g2",
    score: 88,
    effortLevel: "MEDIUM",
    summary:
      "This initiative provides fixed $50,000 awards to nonprofits running structured mentorship programs for youth aged 10–18 in low-income neighborhoods. Applicants must demonstrate at least two years of program history and serve a minimum of 50 youth annually. A full proposal with outcome data, budget narrative, and organizational financials is required.",
    reasoning:
      "Strong fit for Horizon's mentorship programming. Requires outcome data you likely have; two-year history requirement is met.",
    grant: {
      id: "g2",
      externalId: "grants.gov-512044",
      title: "After-School Enrichment Initiative",
      funder: "Nexus National Trust",
      deadline: new Date(Date.now() + 47 * 24 * 60 * 60 * 1000).toISOString(),
      amountMin: 50000,
      amountMax: 50000,
      eligibility: ["Nonprofits (501c3)"],
      description: "Funds structured after-school mentorship and enrichment programs for youth in low-income areas.",
      category: ["Mentorship", "Youth Development"],
      sourceUrl: "https://www.grants.gov/search-results-detail/512044",
      source: "grants.gov",
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "m3",
    orgId: DEMO_ORG_ID,
    grantId: "g3",
    score: 82,
    effortLevel: "HIGH",
    summary:
      "The NextGen Leaders Fellowship funds general operating support for nonprofits building youth leadership pipelines, with awards up to $250,000 over two years. Eligible organizations must have annual budgets under $2M and serve youth from historically marginalized communities. Applications open with a Letter of Inquiry, followed by an invitation-only full proposal.",
    reasoning:
      "High award ceiling is compelling. LOI-first process reduces upfront effort; strong mission alignment on youth leadership.",
    grant: {
      id: "g3",
      externalId: "grants.gov-389201",
      title: "NextGen Leaders Fellowship Focus",
      funder: "The Starlight Global Fund",
      deadline: new Date(Date.now() + 104 * 24 * 60 * 60 * 1000).toISOString(),
      amountMin: 100000,
      amountMax: 250000,
      eligibility: ["Nonprofits (501c3)", "Nonprofits (no 501c3 restriction)"],
      description: "General operating support for nonprofits developing youth leadership in marginalized communities.",
      category: ["General Operating", "Youth Leadership"],
      sourceUrl: "https://www.grants.gov/search-results-detail/389201",
      source: "grants.gov",
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "m4",
    orgId: DEMO_ORG_ID,
    grantId: "g4",
    score: 76,
    effortLevel: "LOW",
    summary:
      "This micro-grant program awards $5,000 to community organizations running neighborhood wellness and enrichment activities. Local nonprofits and community groups within Chicago city limits are eligible with no minimum budget requirement. Applications are a simple two-page online form with no attachments required.",
    reasoning:
      "Low effort and fast turnaround make this worth applying despite the smaller award. Strong geographic fit for Chicago-based work.",
    grant: {
      id: "g4",
      externalId: "grants.gov-601774",
      title: "Neighborhood Wellness Micro-Grant",
      funder: "Metro Arts & Parks Dept",
      deadline: new Date(Date.now() + 73 * 24 * 60 * 60 * 1000).toISOString(),
      amountMin: 5000,
      amountMax: 5000,
      eligibility: ["Nonprofits (no 501c3 restriction)", "City governments"],
      description: "Supports neighborhood-level wellness, arts, and enrichment programs in Chicago.",
      category: ["Community Wellness", "Local Focus"],
      sourceUrl: "https://www.grants.gov/search-results-detail/601774",
      source: "grants.gov",
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "m5",
    orgId: DEMO_ORG_ID,
    grantId: "g5",
    score: 71,
    effortLevel: "MEDIUM",
    summary:
      "This federal program funds school-community partnerships that expand access to mental health services for K-12 students in Title I schools. Nonprofit applicants must partner with at least one public school district and demonstrate community need with local data. A full federal application is required including SF-424 forms, a logic model, and a detailed evaluation plan.",
    reasoning:
      "Mental health focus aligns with Horizon's holistic youth support model. Requires a school district partner — achievable given your existing relationships.",
    grant: {
      id: "g5",
      externalId: "grants.gov-478330",
      title: "Student Wellness Partnership Program",
      funder: "Dept. of Education — OESE",
      deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
      amountMin: 75000,
      amountMax: 150000,
      eligibility: ["Nonprofits (501c3)", "Independent school districts"],
      description: "Expands mental health services in Title I schools through nonprofit-school partnerships.",
      category: ["Mental Health", "Education"],
      sourceUrl: "https://www.grants.gov/search-results-detail/478330",
      source: "grants.gov",
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  },
  {
    id: "m6",
    orgId: DEMO_ORG_ID,
    grantId: "g6",
    score: 64,
    effortLevel: "LOW",
    summary:
      "The Digital Inclusion Fund provides equipment grants of up to $15,000 for nonprofits distributing refurbished devices and internet access to low-income households. Organizations must serve households earning below 200% of the federal poverty line and provide basic digital literacy training. Application is a short online form reviewed on a rolling basis.",
    reasoning:
      "Moderate fit — Horizon's STEM focus overlaps with digital access work, though this is more equipment/access focused than programming.",
    grant: {
      id: "g6",
      externalId: "grants.gov-523901",
      title: "Digital Inclusion Fund",
      funder: "Connect America Initiative",
      deadline: null,
      amountMin: 5000,
      amountMax: 15000,
      eligibility: ["Nonprofits (501c3)"],
      description: "Equipment and connectivity grants for nonprofits bridging the digital divide in low-income communities.",
      category: ["Digital Access", "Technology"],
      sourceUrl: "https://www.grants.gov/search-results-detail/523901",
      source: "grants.gov",
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  },
];

export const demoSaved: SavedGrant[] = [
  {
    id: "s1",
    orgId: DEMO_ORG_ID,
    grantId: "g1",
    notes: "Reach out to program officer before applying.",
    reminder30: false,
    reminder7: false,
    createdAt: new Date().toISOString(),
    grant: demoMatches[0].grant,
  },
  {
    id: "s2",
    orgId: DEMO_ORG_ID,
    grantId: "g2",
    notes: null,
    reminder30: true,
    reminder7: false,
    createdAt: new Date().toISOString(),
    grant: demoMatches[1].grant,
  },
  {
    id: "s3",
    orgId: DEMO_ORG_ID,
    grantId: "g5",
    notes: "Need to confirm school district partner first.",
    reminder30: false,
    reminder7: false,
    createdAt: new Date().toISOString(),
    grant: demoMatches[4].grant,
  },
];
